//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Sage.SData.Repository;
namespace BillableModel.Models
{
    [DataContract]
    public partial class Contact : SDataModelEntity
    {
    	[DataMember]
        public int ContactID { get; set; }
    	[DataMember]
        public int CustomerID { get; set; }
    	[DataMember]
        public string ContactName { get; set; }
    	[DataMember]
        public string ContactTitle { get; set; }
    	[DataMember]
        public string OfficeEmailAddress { get; set; }
    	[DataMember]
        public string PersonalEmailAddress { get; set; }
    	[DataMember]
        public string OfficePhone { get; set; }
    	[DataMember]
        public string CellPhone { get; set; }
    	[DataMember]
        public string HomePhone { get; set; }
    }
    
}
