//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Sage.SData.Repository;
namespace BillableModel.Models
{
    [DataContract]
    public partial class Customer : SDataModelEntity
    {
    	[DataMember]
        public int CustomerID { get; set; }
    	[DataMember]
        public string CustomerName { get; set; }
    	[DataMember]
        public string CustomerKey { get; set; }
    	[DataMember]
        public int TenantID { get; set; }
    	[DataMember]
        public string StreetAddress { get; set; }
    	[DataMember]
        public string City { get; set; }
    	[DataMember]
        public string StateProvince { get; set; }
    	[DataMember]
        public string PostalCode { get; set; }
    	[DataMember]
        public string Phone { get; set; }
    	[DataMember]
        public int AccountType { get; set; }
    }
    
}
