//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace BillableModel.Models
{
    public partial class BillableServicesEntities : DbContext
    {
        public BillableServicesEntities()
            : base("name=BillableServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BillingSchedule> BillingSchedules { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ServiceCharge> ServiceCharges { get; set; }
        public DbSet<ServiceDetail> ServiceDetails { get; set; }
        public DbSet<ServiceType> ServiceTypes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<vwBillingDetail> vwBillingDetails { get; set; }
        public DbSet<vwBillingDetailIndex> vwBillingDetailIndexes { get; set; }
        public DbSet<vwBillingSchedule> vwBillingSchedules { get; set; }
        public DbSet<vwClientServiceCharge> vwClientServiceCharges { get; set; }
        public DbSet<vwProject> vwProjects { get; set; }
        public DbSet<vwsContact> vwsContacts { get; set; }
        public DbSet<vwsCustomer> vwsCustomers { get; set; }
        public DbSet<vwServiceCharge> vwServiceCharges { get; set; }
        public DbSet<vwsProject> vwsProjects { get; set; }
        public DbSet<vwsServiceChargeDetail> vwsServiceChargeDetails { get; set; }
        public DbSet<vwsServiceCharge> vwsServiceCharges { get; set; }
        public DbSet<vwsServiceType> vwsServiceTypes { get; set; }
        public DbSet<vwsUserChargesDaily> vwsUserChargesDailies { get; set; }
        public DbSet<vwsUser> vwsUsers { get; set; }
        public DbSet<vwTenantChargesDaily> vwTenantChargesDailies { get; set; }
        public DbSet<vwTenantChargesMonthly> vwTenantChargesMonthlies { get; set; }
        public DbSet<vwTenantChargesWeekly> vwTenantChargesWeeklies { get; set; }
    }
}
