//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace BillableModel.Models
{
    public partial class BillableServicesEntities : DbContext
    {
        public BillableServicesEntities()
            : base("name=BillableServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BillingSchedule> BillingSchedules { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ServiceCharge> ServiceCharges { get; set; }
        public DbSet<ServiceDetail> ServiceDetails { get; set; }
        public DbSet<ServiceType> ServiceTypes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<vwsUser> vwsUsers { get; set; }
        public DbSet<vwsUserChargesDaily> vwsUserChargesDailies { get; set; }
        public DbSet<vwsProject> vwsProjects { get; set; }
        public DbSet<vwsServiceCharge> vwsServiceCharges { get; set; }
    }
}
