//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Sage.SData.Repository;
namespace BillableModel.Models
{
    [DataContract]
    public partial class Project : SDataModelEntity
    {
        public Project()
        {
            this.ServiceCharges = new HashSet<ServiceCharge>();
        }
    
    	[DataMember]
        public int ProjectID { get; set; }
    	[DataMember]
        public string ProjectDescription { get; set; }
    	[DataMember]
        public System.DateTime ProjectDate { get; set; }
    	[DataMember]
        public int CustomerID { get; set; }
    	[DataMember]
        public double Budget { get; set; }
    	[DataMember]
        public double BilledAmt { get; set; }
    
        public virtual ICollection<ServiceCharge> ServiceCharges { get; set; }
    }
    
}
