//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Sage.SData.Repository;
namespace BillableModel.Models
{
    [DataContract]
    public partial class ServiceType : SDataModelEntity
    {
        public ServiceType()
        {
            this.ServiceDetails = new HashSet<ServiceDetail>();
        }
    
    	[DataMember]
        public int ServiceTypeID { get; set; }
    	[DataMember]
        public string ServiceDescription { get; set; }
    	[DataMember]
        public Nullable<int> TenantID { get; set; }
    	[DataMember]
        public string UOM { get; set; }
    	[DataMember]
        public double Rate { get; set; }
    	[DataMember]
        public string Taxable { get; set; }
    
    	[DataMember]
        public virtual ICollection<ServiceDetail> ServiceDetails { get; set; }
    }
    
}
