//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using SDataRepository;

namespace BillableModel.Models
{
    [DataContract]
    public partial class vwBillingDetail : MobileModelEntity
    {
    	[DataMember]
        public int CustomerID { get; set; }
    	[DataMember]
        public string CustomerName { get; set; }
    	[DataMember]
        public int TenantID { get; set; }
    	[DataMember]
        public int ServiceChargeID { get; set; }
    	[DataMember]
        public string Ticket { get; set; }
    	[DataMember]
        public System.DateTime ServiceDate { get; set; }
    	[DataMember]
        public int Status { get; set; }
    	[DataMember]
        public int PaymentMethod { get; set; }
    	[DataMember]
        public string ServiceChargeNote { get; set; }
    	[DataMember]
        public Nullable<int> NumCharges { get; set; }
    	[DataMember]
        public int ProjectID { get; set; }
    	[DataMember]
        public string ProjectDescription { get; set; }
    	[DataMember]
        public int ServiceTypeID { get; set; }
    	[DataMember]
        public string ServiceDescription { get; set; }
    	[DataMember]
        public int ServiceDetailsID { get; set; }
    	[DataMember]
        public string ServiceDetailNote { get; set; }
    	[DataMember]
        public double Rate { get; set; }
    	[DataMember]
        public double Qty { get; set; }
    	[DataMember]
        public string Taxable { get; set; }
    	[DataMember]
        public double Amount { get; set; }
    }
    
}
