//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using SDataRepository;

namespace BillableModel.Models
{
    [DataContract]
    public partial class vwProject : MobileModelEntity
    {
    	[DataMember]
        public int ProjectID { get; set; }
    	[DataMember]
        public string ProjectDescription { get; set; }
    	[DataMember]
        public string CustomerName { get; set; }
    	[DataMember]
        public double Budget { get; set; }
    	[DataMember]
        public int TenantID { get; set; }
    }
    
}
